import {
  countSnapshotItems,
  validateSessionSnapshotPayload,
} from '@/services/session-snapshot-codec'
import {
  isTabsOutlinerImport,
  parseTabsOutlinerImport,
} from '@/services/session-snapshot-import-tabs-outliner'
import {
  isSessionBuddyImport,
  parseSessionBuddyImport,
} from '@/services/session-snapshot-import-session-buddy'
import {
  isTabSessionManagerImport,
  parseTabSessionManagerImport,
} from '@/services/session-snapshot-import-tab-session-manager'
import {
  SESSION_SNAPSHOT_SCHEMA_VERSION,
  type ParsedSessionSnapshotImport,
} from '@/types/session-snapshots'
import { TreeItemType } from '@/types/session-tree'

// Format adapters end at this boundary; storage and restore only see the
// validated Session Flow snapshot payload.
export function parseSessionSnapshotImport(
  json: string,
): ParsedSessionSnapshotImport {
  let value: unknown
  try {
    value = JSON.parse(json.replace(/^\uFEFF/, ''))
  } catch {
    throw new Error('The selected file is not a valid snapshot file.')
  }

  if (isTabsOutlinerImport(value)) return parseTabsOutlinerImport(value)

  if (isRecord(value) && 'format' in value) {
    if (value.format !== 'session-flow-snapshot') {
      throw new Error(
        'Unsupported import format. Choose a supported snapshot file.',
      )
    }
    if (value.schemaVersion !== SESSION_SNAPSHOT_SCHEMA_VERSION) {
      throw new Error('Unsupported session snapshot schema version')
    }
    // Imported metadata is deliberately regenerated by the background service.
    return sessionFlowImport(
      value.payload,
      isRecord(value.metadata) ? value.metadata.createdAt : undefined,
    )
  }

  if (isRecord(value) && 'schemaVersion' in value) {
    return sessionFlowImport(value)
  }

  if (isTabSessionManagerImport(value))
    return parseTabSessionManagerImport(value)
  if (isSessionBuddyImport(value)) return parseSessionBuddyImport(value)

  // Native trees are either the stored array itself or a storage export.
  const items = Array.isArray(value)
    ? value
    : isRecord(value) && Array.isArray(value.sessionTree)
      ? value.sessionTree
      : undefined
  if (items) {
    return sessionFlowImport({
      schemaVersion: SESSION_SNAPSHOT_SCHEMA_VERSION,
      items: items.map(stripRuntimeFields),
    })
  }

  throw new Error(
    'Unsupported import format. Choose a supported snapshot file.',
  )
}

function sessionFlowImport(
  value: unknown,
  createdAt?: unknown,
): ParsedSessionSnapshotImport {
  const payload = validateSessionSnapshotPayload(value)
  return {
    payload,
    summary: {
      source: 'session-flow',
      ...(typeof createdAt === 'number' &&
      Number.isFinite(new Date(createdAt).getTime())
        ? { sourceCreatedAt: createdAt }
        : {}),
      counts: countSnapshotItems(payload.items),
      warnings: [],
    },
  }
}

function stripRuntimeFields(value: unknown): unknown {
  if (!isRecord(value)) return value
  const item = { ...value }
  for (const field of [
    'id',
    'active',
    'activeTabId',
    'selected',
    'loadingStatus',
    'isVisible',
  ]) {
    delete item[field]
  }
  if (item.type === TreeItemType.WINDOW && Array.isArray(item.children)) {
    item.children = item.children.map(stripRuntimeFields)
  }
  if (item.type === TreeItemType.TAB && isRecord(item.tabGroup)) {
    item.tabGroup = { ...item.tabGroup }
    delete (item.tabGroup as Record<string, unknown>).id
  }
  return item
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value)
}
